dist: trusty
sudo: required
language:
  - generic
cache:
  - apt
services:
  - docker

install:
  - docker pull vortexntnu/rov-control

script:
  - docker run -v $(pwd):/root/clone vortexntnu/rov-control bash -c "source /opt/ros/kinetic/setup.bash && mkdir -p ~/catkin_ws/src && cd ~/catkin_ws/src && catkin_init_workspace && ln -s /root/clone . && cd ~/catkin_ws && catkin_make && catkin_make tests && source devel/setup.bash && catkin_make run_tests"
