pwm:
  pins:
    claw_servo: 9
  frequency:
    set: 249.0
    measured: 251.2
  counter:
    max: 4095

servo:
  lookup:
    position: [-1, 1]
    pulse_width: [1500, 1100]

stepper:
  default_speed_rpm: 30
  steps_per_rev: 200
  pins:
    valve: [2, 3, 4, 17]

computer: 'pc-debug'
