# This file defines parameters specific to the Terrapin ROV
#
# When looking at the ROV from above, the thruster placement is:
#     ____
# ↗8 /    \ 1↖
# ⨯7|      |2⨯
# ⨯6|      |3⨯
# ↘5 \____/ 4↙

physical:
  mass_kg: 0
  displacement_m3: 0
  center_of_mass: [0, 0, 0]
  center_of_buoyancy: [0, 0, 0]

propulsion:
  dofs:
    num: 6
    which:
      surge: true
      sway:  true
      heave: true
      roll:  true
      pitch: true
      yaw:   true
  thrusters:
    num: 8
    configuration_matrix:
      [[ 0.70711,  0.00000,  0.00000, -0.70711, -0.70711,  0.00000,  0.00000, 0.70711], # Surge
       [-0.70711,  0.00000,  0.00000, -0.70711,  0.70711,  0.00000,  0.00000, 0.70711], # Sway
       [ 0.00000,  1.00000,  1.00000,  0.00000,  0.00000,  1.00000,  1.00000, 0.00000], # Heave
       [ 0.00000,  0.15800,  0.15800,  0.00000,  0.00000, -0.15800, -0.15800, 0.00000], # Roll
       [ 0.00000, -0.06600,  0.06600,  0.00000,  0.00000,  0.06600, -0.06600, 0.00000], # Pitch
       [-0.20577, -0.00000, -0.00000,  0.20577, -0.20577,  0.00000,  0.00000, 0.20577]] # Yaw
  command:
    wrench:
      max:     [33.9, 33.9, 48.0, 7.6, 3.2, 9.9]
      scaling: [ 0.2,  0.2,  0.5, 0.5, 1.0, 0.2]
    pose:
      rate: [0.20, 0.20, 0.20, 0.35, 0.35, 0.35] # Euler angle pose!

controller:
  gains:
    a: 0.0
    b: 100.0
    c: 20.0
  frequency: 10

servo:
  lookup:
    position: [-1, 1]
    pulse_width: [1500, 1100]

stepper:
  default_speed_rpm: 30
  steps_per_rev: 200
  pins:
    valve: ['P9_01', 'P9_02', 'P9_03', 'P9_04']

pwm:
  pins:
    claw_servo: 9
  frequency:
    set: 249.0
    measured: 251.2
  counter:
    max: 4095

light:
  gpio_pins: {"bluetooth":"P8_7", "raman":"P8_8"}
  pwm_pins: {"front": 8}
